version: "3.2"
services:
  mongo-service:
    image: ${MONGO_IMAGE_NAME}
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DB_PATH}:/data:rw
    ports:
      - "0.0.0.0:${MONGO_EXTERIOR_PORT}:${MONGO_CONTAINER_PORT}"
    restart: on-failure
